In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/students-grading-dataset/Students_Grading_Dataset.csv
/kaggle/input/students-grading-dataset/metadata.xlsx
/kaggle/input/students-grading-dataset/Students_Grading_Dataset.json

In [3]:
df = pd.read_csv('/kaggle/input/students-grading-dataset/Students_Grading_Dataset.csv')
df.info()
df.head()  # Посмотрим первые 5 строк

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Student_ID                  5000 non-null   object
 1   First_Name                  5000 non-null   object
 2   Last_Name                   5000 non-null   object
 3   Email                       5000 non-null   object
 4   Gender                      5000 non-null   object
 5   Age                         5000 non-null   int64
 6   Department                  5000 non-null   object
 7   Attendance (%)              4484 non-null   float64
 8   Midterm_Score               5000 non-null   float64
 9   Final_Score                 5000 non-null   float64
 10  Assignments_Avg             4483 non-null   float64
 11  Quizzes_Avg                 5000 non-null   float64
 12  Participation_Score         5000 non-null   float64
 13  Projects_Score              5000 non-null   float64
 14  Total_Score                 5000 non-null   float64
 15  Grade                       5000 non-null   object
 16  Study_Hours_per_Week        5000 non-null   float64
 17  Extracurricular_Activities  5000 non-null   object
 18  Internet_Access_at_Home     5000 non-null   object
 19  Parent_Education_Level      3206 non-null   object
 20  Family_Income_Level         5000 non-null   object
 21  Stress_Level (1-10)         5000 non-null   int64
 22  Sleep_Hours_per_Night       5000 non-null   float64
dtypes: float64(10), int64(2), object(11)
memory usage: 898.6+ KB

,Student_ID,First_Name,Last_Name,Email,Gender,Age,Department,Attendance (%),Midterm_Score,Final_Score,...,Projects_Score,Total_Score,Grade,Study_Hours_per_Week,Extracurricular_Activities,Internet_Access_at_Home,Parent_Education_Level,Family_Income_Level,Stress_Level (1-10),Sleep_Hours_per_Night
0,S1000,Omar,Williams,student0@university.com,Female,22,Engineering,52.29,55.03,57.82,...,85.90,56.09,F,6.2,No,Yes,High School,Medium,5,4.7
1,S1001,Maria,Brown,student1@university.com,Male,18,Engineering,97.27,97.23,45.80,...,55.65,50.64,A,19.0,No,Yes,NaN,Medium,4,9.0
2,S1002,Ahmed,Jones,student2@university.com,Male,24,Business,57.19,67.05,93.68,...,73.79,70.30,D,20.7,No,Yes,Master's,Low,6,6.2
3,S1003,Omar,Williams,student3@university.com,Female,24,Mathematics,95.15,47.79,80.63,...,92.12,61.63,A,24.8,Yes,Yes,High School,High,3,6.7
4,S1004,John,Smith,student4@university.com,Female,23,CS,54.18,46.59,78.89,...,68.42,66.13,F,15.4,Yes,Yes,High School,High,2,7.1

In [8]:
#df_meta = pd.read_excel('/kaggle/input/students-grading-dataset/metadata.xlsx')
#print(df_meta.head(100))

In [7]:
#df_json = pd.read_json('/kaggle/input/students-grading-dataset/Students_Grading_Dataset.json')
#print(df_json.head())

In [4]:
# Работа с пропущенными значениями

# кол-во пропущенных значений в каждом столбце 
no_data = df.isna().sum()
print(no_data)

# топ 3 столбца с бОльшим кол-вом пропусков
no_data.sort_values(ascending = False).head(3)

# заполнение пропущенных значений
df['Parent_Education_Level'] = df['Parent_Education_Level'].fillna('unknown')
df['Assignments_Avg'] = df['Assignments_Avg'].fillna('0')
df['Attendance (%)'] = df['Attendance (%)'].fillna('0')

print(df.isna().sum())

Student_ID                       0
First_Name                       0
Last_Name                        0
Email                            0
Gender                           0
Age                              0
Department                       0
Attendance (%)                 516
Midterm_Score                    0
Final_Score                      0
Assignments_Avg                517
Quizzes_Avg                      0
Participation_Score              0
Projects_Score                   0
Total_Score                      0
Grade                            0
Study_Hours_per_Week             0
Extracurricular_Activities       0
Internet_Access_at_Home          0
Parent_Education_Level        1794
Family_Income_Level              0
Stress_Level (1-10)              0
Sleep_Hours_per_Night            0
dtype: int64
Student_ID                    0
First_Name                    0
Last_Name                     0
Email                         0
Gender                        0
Age                           0
Department                    0
Attendance (%)                0
Midterm_Score                 0
Final_Score                   0
Assignments_Avg               0
Quizzes_Avg                   0
Participation_Score           0
Projects_Score                0
Total_Score                   0
Grade                         0
Study_Hours_per_Week          0
Extracurricular_Activities    0
Internet_Access_at_Home       0
Parent_Education_Level        0
Family_Income_Level           0
Stress_Level (1-10)           0
Sleep_Hours_per_Night         0
dtype: int64

In [8]:
# группировка и агрегирование 

# средний балл (Total_Score) для каждого Department
group_1 = df.groupby('Department')['Total_Score'].mean()
print(group_1)

# какой департамент имеет самый высокий средний балл
gpoup_1.sort_value(ascending=False).head(1)

Department
Business       74.495060
CS             75.396612
Engineering    75.020088
Mathematics    75.567654
Name: Total_Score, dtype: float64

NameError: name 'gpoup_1' is not defined

In [54]:
# создание новой категории Attendance_Category

def categorize_attendance(arr):
    if float(arr) > 90:
        return "Excellent"
    elif 50 <= float(arr) <= 90:
        return 'Average'
    else:
        return 'Poor'

df['Attendance_Category'] = df['Attendance (%)'].apply(categorize_attendance)
df[['Student_ID','Attendance (%)','Attendance_Category']].head()

  Student_ID Attendance (%) Attendance_Category
0      S1000          52.29             Average
1      S1001          97.27           Excellent
2      S1002          57.19             Average
3      S1003          95.15           Excellent
4      S1004          54.18             Average

In [52]:
# сравнение результатов экзаменов

df['Improved'] = df.apply(lambda arr: arr['Final_Score'] > arr['Midterm_Score'], axis = 1)
df[['Student_ID','Midterm_Score','Final_Score','Improved']].head()

  Student_ID  Midterm_Score  Final_Score  Improved
0      S1000          55.03        57.82      True
1      S1001          97.23        45.80     False
2      S1002          67.05        93.68      True
3      S1003          47.79        80.63      True
4      S1004          46.59        78.89      True